### ISSUE TITLE
Question: query without Promise.using

### ISSUE THREAD

**Issue by jrnail23** [lanetix/node-pg-connect#6]
Hey @apechimp, as I was playing around with pg-connect, it struck me that the `withTransaction` usage is actually simpler than the (probably more often used) simple query case (since you really need to use `Promise.using` for those, while the `withTransaction` case can be used without the consuming code needing bluebird).

It seems like it would be a nice improvement to the api to have a non-transactional query method that also wraps the `Promise.using` in a similar way to what `withTransaction` does.  

What do you think?

**Comment by apechimp** [comment]
Sounds reasonable. :+1:

**Comment by apechimp** [comment]
This package is now deprecated.
